var edgekv_access_tokens = {
"namespace-tokenAuth" : { 
"name": "smptoken",
"value" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJld2lkcyI6ImFsbCIsInN1YiI6IjgyNzAiLCJjcGMiOiIxMDk4MTY3IiwiaXNzIjoiYWthbWFpLmNvbS9FZGdlREIvUHVsc2FyL3YwLjkuMCIsIm5hbWVzcGFjZS10b2tlbkF1dGgiOlsiciJdLCJleHAiOjE2NDA5MDg3OTksImVudiI6WyJwIiwicyJdLCJpYXQiOjE2Mjg0OTI4NjMsImp0aSI6Ijk2MmZkOTQ1LTdkMDQtNTJmNS1hMzVmLWU5NWJmN2U2Y2QxYyIsInJlcWlkIjoiYWthbWFpIiwibm9lY2wiOnRydWV9.cKazOo-L-9vcjB9HluBH7Ga6wOCXMlHHKYqnyMr5Is34FGd_qZL6kOYOSDDhH04vT9O0onKyV_nbRGGUwTi9HpvnCh9Nem6HtteJsz0QgCFJm_tIN3SxiZtkdYvXoNuYACAtE1C0A6WjxNXahGkUlVoK2USanXImuIYwYi8zlUmolcZJdm8wB3uhJRY2qJc1ttdnfjHN6lEHo_rZEoyhLVqoX2CK0YeAJAf--jJ8hMLxoybGEPMUpq4Gmu8qkHhpF9oGpTJMex66odejbpLvE8UQKApNjNuLzpyxO448gqJLPa1m5htQJCbEapBUOTKXYT0phBz8fRFkJTZvUuyOZA"
}
}
export { edgekv_access_tokens };